### ISSUE TITLE
Unclear prompt about free space

### ISSUE THREAD

**Issue by bdimych** [datorrukis/freenet-installer#10]
the prompt is "percentage of freespace in % or GB (freespace: 15.45 G) (default: -1):"
questions:
1) "percentage in GB" sounds senseless,
2) there is no clear instruction of how to specify number - 10g or 10gb or just 10?
3) and what does it mean "-1"?
4) "free space" should be two words,

**Comment by datorrukis** [comment]
- 1 true (changed)
- 2, all the versions works (10 10g 10G 10GB 10 gb ...)
- 3, change to auto (for configuration like freenet is doing when specifing -1)
- 4 done
